### ISSUE TITLE
U2Net Portrait Drawing Demo 

### ISSUE THREAD

**Issue by NaeemKhan333** [w-okada/image-analyze-workers#13]
@w-okada Thanks for nice work . I am running the demo link for U2Net Portrait Drawing. I cannot see any demo on the given link.It is showing the following 

![Screenshot from 2021-01-22 18-16-55](https://user-images.githubusercontent.com/52487215/105495816-6f049b00-5cde-11eb-90e1-5e577cc4c263.png)

https://flect-lab-web.s3-us-west-2.amazonaws.com/P01_wokers/t09_u2net-portrait/index.html

Can you guide about it .Thank you

**Comment by dannadori** [comment]
What is your OS and browser.
I am using windows10 and chrome and I can see.
It's very big model so please wait a few minutes.

**Comment by NaeemKhan333** [comment]
@dannadori can you tell me what repository you have used for running the model in browser.I can see two folders

Folder1 : 009_u2net-portrait-worker-js

```
https://github.com/w-okada/image-analyze-workers/tree/master/009_u2net-portrait-worker-js
```

Folder2: 009demo_u2net-portrait-worker-js-demo

```
https://github.com/w-okada/image-analyze-workers/tree/master/009demo_u2net-portrait-worker-js-demo
```
Can you tell me which repository is used for the demo on web browser.What is difference between the these repositories.Thanks

**Comment by dannadori** [comment]
Folder2. 

Folder1 is libraly which is used in Folder2

**Comment by NaeemKhan333** [comment]
@dannadori can you have a web code which is working for video stream on the web browser.

**Comment by w-okada** [comment]
@NaeemKhan333 

Sorry, I can not understand what you said.
Folder 1 and folder 2 are all I have. If you want to have more feature, please be more concrete.
What do you want to have? But, note, I can publish or not depends on the case.

**Comment by NaeemKhan333** [comment]
@dannadori Thanks for response. I am asking that Does you have a repository or code which support the u2net model webcam inferences on web browser.Thanks

**Comment by w-okada** [comment]
@NaeemKhan333
You can change input device or file from control panel of demo page.
But this model is very heavy and response is very bad, so I don't recommend to use it with webcam.

**Comment by NaeemKhan333** [comment]
ok thank you for help.

**Comment by NaeemKhan333** [comment]
@dannadori Hope you are doing well . I have a question related to the output of u2netp conversion to Tensor.js format. After sucessful conversion , I get three files

```
- model.json
- group1-shard1of2.bin
- group1-shard2of2.bin
```
But in the web demo of u2net portrait, I have seen 42 bin files, group1-shard42of42.bin.
Q1-Can you tell me about 'bin file' and what is their role?
Q2-Does this code support u2net model for the inferences on the Web Browser?Because my converted model does not show any output on your code.Thanks

**Comment by w-okada** [comment]
Please contact to tensorflowjs team. This is not the repository for tensorflowjs or its converter.

Same as this.
https://github.com/w-okada/image-analyze-workers/issues/11

I close once.

**Comment by NaeemKhan333** [comment]
@dannadori I have followed each and every step exactly as mentioned in the Blog . But my own converted model is not working in the u2net portrait web Demo . Can you provide the docker image of the environment which you have setup. It is highly appreciable because I am stuck in it.Thanks
