### ISSUE TITLE
ImportError: libinference_engine.so Openvino to Tensorflow

### ISSUE THREAD

**Issue by NaeemKhan333** [w-okada/image-analyze-workers#14]
Thanks @w-okada for help . I am running following command and getting the error

openvino2tensorflow --model_path openvino/320x320/FP32/u2net_320x320_opt.xml --model_output_path saved_model_320x320 --output_saved_model True

Traceback (most recent call last):
  File "/home/user/.local/bin/openvino2tensorflow", line 66, in <module>
    from openvino.inference_engine import IECore
  File "/home/naeem/.local/lib/python3.6/site-packages/openvino/inference_engine/__init__.py", line 1, in <module>
    from .ie_api import *
ImportError: libinference_engine.so: cannot open shared object file: No such file or directory

Can you guide me what I am doing wrong.Thanks

**Comment by dannadori** [comment]
Same issue?
https://github.com/w-okada/image-analyze-workers/issues/11

And please try to follow my blog process exactly.

**Comment by NaeemKhan333** [comment]
@dannadori I have followed your blog process , once it is converted successfully but now I am getting above error which is different error from the error #11 .I do not know but getting this error . Can you help me out .Thanks
