### ISSUE TITLE
Demo Google Meet Person Segmentation

### ISSUE THREAD

**Issue by NaeemKhan333** [w-okada/image-analyze-workers#15]
@w-okada Thanks for nice work . I have seen two repositories related to "Google meet person segmentation" in your github. 

```
https://github.com/w-okada/image-analyze-workers/tree/master/011_googlemeet-segmentation-worker-js
https://github.com/w-okada/image-analyze-workers/tree/master/011demo_googlemeet-segmentation-worker-js-demo
```

I have two Question

1- Can you provide me the source link (Orignal(Training) Code Repository) which is used for designing the Browser Web App?
2- Can "Google Meet Person Segmentation" Work in Real Time Segmentation on 720p resolution video?

I Will Wait for your response .Thanks

**Comment by w-okada** [comment]
A1. The source code of the demo is 
 https://github.com/w-okada/image-analyze-workers/tree/master/011demo_googlemeet-segmentation-worker-js-demo
A2. Please try to use the demo page. You can input your image you want to check.

**Comment by NaeemKhan333** [comment]
@w-okada Thanks for response. Can you have source code for training of "Google meet person segmentation"?

**Comment by w-okada** [comment]
持っていません。google mediapipeチームにご相談してはいかがでしょうか。
一度閉じます。
