### ISSUE TITLE
U2net Converted Model Not Working in Web Demo 

### ISSUE THREAD

**Issue by NaeemKhan333** [w-okada/image-analyze-workers#17]
@w-okada Thanks for nice work. I have converted the 

-> U2net model to Tensorflow Js

Using the process given inside the blog.It is converted successfully and get the model in TensorFlow JS format.

Secondly , I run the U2net Portrait web Demo on local cpu machine and it work fine on the converted u2net portrait model given by you in the web demo code. But when I replace my own converted u2net model in the web demo code .It does not giving any result.Can you recheck whether the method is converting(u2net and u2netp) rightly and will it compatible with the web app.Thanks

**Comment by w-okada** [comment]
I confirmed. And other user also report me that he can convert it.
Please check your operation.

**Comment by NaeemKhan333** [comment]
@w-okada thank you for response, I also done the conversion successfully but when I replaced the folder u2net-portrait model with u2net model in the given web demo.It give me nothing in the output.So I am considering there is something went wrong in the conversion. Have you converted the u2net model,run the converted model in to the web browser demo and is it working ?

**Comment by w-okada** [comment]
My demo uses the U^2net for portrait. If you use another model, you must edit  the code to handle the model.  I have no plan to apply my code to arbitry model.

**Comment by NaeemKhan333** [comment]
Is it Gpu is necessary for conversion? or we can do conversion using cpu as well?

**Comment by NaeemKhan333** [comment]
I have converted u2net-portrait model using your blog, But when I put this converted model in the web demo ,it does not work for me.
