### ISSUE TITLE
Openvino2tensorflow : Segmentation fault (core dumped) 

### ISSUE THREAD

**Issue by NaeemKhan333** [w-okada/image-analyze-workers#18]
@w-okada Thank you for response . I am trying to convert the u2net model to tensorflow Js. I am getting error while I run the following command
```
openvino2tensorflow --model_path openvino/320x320/FP32/u2net_320x320_opt.xml --model_output_path saved_model_320x320 --output_saved_model True

Segmentation fault (core dumped)
```
I am using python 3.8 and openvino2021 for the conversion of model.Thanks

**Comment by w-okada** [comment]
This repository is not for openvino2tensorflow.

Same as this.
https://github.com/w-okada/image-analyze-workers/issues/11

I close once.

**Comment by NaeemKhan333** [comment]
By running the following command, I solve the above issue 

```
source /home/naeem/intel/openvino_2021/bin/setupvars.sh
```
