### ISSUE TITLE
Built Docker environment Taking Too Much Time

### ISSUE THREAD

**Issue by NaeemKhan333** [w-okada/image-analyze-workers#20]
Thanks @w-okada for such a nice work . 

->  U2Net Conversion : Convert PyTorch model to tensorflowjs [Blog-Link](https://dannadori.medium.com/convert-pytorch-model-to-tensorflowjs-fb3bc8e90589)

I have run the docker container which have Ubuntu and Cuda version 10.1.Then I start installing related packages which is mentioned in the blog.But when I run the following command

```
pip3 install onnxruntime onnx-simplifier openvino-python --upgrade
```
Its takes many hours to complete . Is same thing happens with you or it is abnormal .Thanks

**Comment by NaeemKhan333** [comment]
@w-okada waiting for response because I could not resolve the issues and stuck in conversion . Response will be highly appreciable and helpful.Thanks

**Comment by w-okada** [comment]
I have no experience such that. And I guess the version of the module is conflict or so. 
But now you could convert the model. I close this issue.

https://github.com/w-okada/image-analyze-workers/issues/23

**Comment by josephrocca** [comment]
@NaeemKhan333 @w-okada I had this problem and changed `openvino-python` to `openvino`, which fixed it. Seems to be a problem with incompatible dependencies. This also means you need to use download and install the `2021 3` openvino version instead of `2021 1`.
