### ISSUE TITLE
U2Net Conversion : Docker Image

### ISSUE THREAD

**Issue by NaeemKhan333** [w-okada/image-analyze-workers#21]
@w-okada Thanks for nice . I tried to convert the u2net-portrait model and it is successfully converted.But when I replace this model in the web demo . It does not work for me in the web demo . I am using following

- [U2-Net Portrait Model](https://drive.google.com/file/d/1IG3HdpcRiDoWNookbncQjeaPN28t90yW/view)

- [Conversion Blog](https://medium.com/analytics-vidhya/generate-portrait-on-browser-with-u%C2%B2-net-71b4c682df44)

I have followed each and every step exactly as mentioned in the Blog . But model is not working in the u2net portrait web Demo . Can you provide the docker image of the environment which you have setup. It is highly appreciable because I am stuck in it.Thanks

**Comment by NaeemKhan333** [comment]
@w-okada am waiting for response because I am getting stuck in conversion . Response will be highly appreciable and helpful.Thanks

**Comment by NaeemKhan333** [comment]
Any Help?

**Comment by w-okada** [comment]
I have no experience such that. And I guess the version of the module is conflict or so. 
But now you could convert the model. I close this issue.

https://github.com/w-okada/image-analyze-workers/issues/23
