### ISSUE TITLE
Testing Code For Converted U2netp Tensorflow-Js

### ISSUE THREAD

**Issue by NaeemKhan333** [w-okada/image-analyze-workers#23]
@w-okada Thanks for nice work . I have converted u2netp model using [Blog](https://dannadori.medium.com/convert-pytorch-model-to-tensorflowjs-fb3bc8e90589) and it is converted successfully. Now I want to test the converted model as you did, as the output is shown

![output](https://user-images.githubusercontent.com/52487215/107211903-ffa1e180-6a27-11eb-8621-dee07940d3a7.png)
Can you provide the Testing script,So I can verify my Tensorflow-Js Converted Model is working or not.Thanks

**Comment by w-okada** [comment]
The generated model is normal tensroflowjs model. So you can write code by yourself.
And as I said in ohter issue, this repository is not for the converting model. I close this issue.

**Comment by NaeemKhan333** [comment]
@w-okada I am new with this fiel, So I do not know about tensorflow Js.It will be helpful if you provide the your testing script for testing tensorflow Js model .Thanks
