### ISSUE TITLE
Slow Speed of Converted TFJS Model

### ISSUE THREAD

**Issue by NaeemKhan333** [w-okada/image-analyze-workers#25]
@w-okada Thanks for nice work . I know this is not a place to ask this question but I am getting stuck in this problem.

* I have a question related to speed of the u2net converted model on the web browser.

I have modified the u2net , trained it and test the model . It is giving me 7-10 Fps on local cpu device(not on browser).
For running on the browser for cpu device, I have converted the modified model into tensorflow Js model using your blog.After converting the model , its total weight become 600kb . But when I run it using the web-app, it is too slow , it is giving me less than 1 Fps . Can you guide me , what steps I need to do to increase the inferences speed and Fps rate of my web-app to achience speed like Google meet person segmentation app. Your advice will be helpful for me. Thanks

**Comment by w-okada** [comment]
This question is better asked on StackOverflow since it is not a bug or feature request. There is also a larger community that reads questions there.
