### ISSUE TITLE
Confusion About Parameters "useTFWasmBackend" and "processOnLocal"

### ISSUE THREAD

**Issue by NaeemKhan333** [w-okada/image-analyze-workers#26]
@w-okada Thank you very much for such a nice work . 

Device: Working on CPU Device

I am using your [U2net-Portrait-Demo-App](https://github.com/w-okada/image-analyze-workers/tree/master/009_u2net-portrait-worker-js) for running custom train u2net-portrait model. It is running fine and speed is upto 2 Fps on the webcam. I have confusion related to two parameters which you have used.

"processOnLocal" : Can you explains , what is role of this parameters in the web-app? Because when turn it "On" results output become distorted in white and black screen but fps get increase to 5-6 fps. And When keep it "Off", the output is good and but fps is up to 2 Fps.

"useTFWasmBackend" : Can you explains , what is role of this parameters in the web-app? As per I know , it is tensorflow web assembly for fast CPU execution. But in app , when I keep useTFWasmBackend=false, fps is get higher than useTFWasmBackend=true. Its quite strange for me. 

Can you help me , what actually I am doing wrong or there other thing that I need to change.Thanks

**Comment by NaeemKhan333** [comment]
@w-okada when processOnLocal" is on , then it does not output correctly, there is problem in the code.

**Comment by NaeemKhan333** [comment]
@w-okada output is like this, when processOnLocal" is on in U2net-Portrait-Demo-App

![output_seg](https://user-images.githubusercontent.com/52487215/109147193-8c69d080-7786-11eb-8b1a-591fbff33790.png)

**Comment by w-okada** [comment]
@NaeemKhan333 

My demo code doesn't have model path u2net130. What is that?
Could your check your model is valid at first?

**Comment by NaeemKhan333** [comment]
@w-okada thanks for response. The model u2net130 is my own trained u2net-portrait model with input shape 130x130 . I have tested the online provided [U2net-App-Demo](https://flect-lab-web.s3-us-west-2.amazonaws.com/P01_wokers/t09_u2net-portrait/index.html) by you , the same problem is happening there also , so there is problem or bug in the code when turn the ""processOnLocal" on in the menu.Check you it Please

**Comment by w-okada** [comment]
@NaeemKhan333

Yes, thanks. I fixed it. please pull again.

**Comment by NaeemKhan333** [comment]
@w-okada Thanks for response . I have cloned the repository again and follow the [u2net installation instruction](https://github.com/w-okada/image-analyze-workers/tree/master/009_u2net-portrait-worker-js) but the output is same is already on my local machine as well as I have check the provided [online u2net-demo](https://flect-lab-web.s3-us-west-2.amazonaws.com/P01_wokers/t09_u2net-portrait/index.html).The Result are same . Can you check it please.Thanks

![feb27](https://user-images.githubusercontent.com/52487215/109285787-4f174880-7843-11eb-819d-54ef8781ae45.png)

**Comment by NaeemKhan333** [comment]
@w-okada Thank you very much, I solved the issue by modifying the version in "package.json"

Change:

![bug_seg](https://user-images.githubusercontent.com/52487215/109294995-cfdc4180-784f-11eb-8871-7fce87845cf2.png)

To: 

![bug_seg2](https://user-images.githubusercontent.com/52487215/109295252-3bbeaa00-7850-11eb-9870-2dda96f3673b.png)
