### ISSUE TITLE
Meet Segmentation Model Cpu Utilization

### ISSUE THREAD

**Issue by tulasiram58827** [w-okada/image-analyze-workers#27]
Firstly Thank you so much @w-okada for creating this project.

I have been using the meet segmentation model it is performing very well but CPU utilization is also very high. This model is using two cores completely. Is there any way to reduce the CPU utilization?

**Comment by w-okada** [comment]
What is your environment? use Webgl? and how may fps is acheived in your environment?

If you can get more than 15 or fps, you can throttle the fps to reduce the CPU utilization. Generally, FPS is 15 or so is enough to use video conference.

**Comment by tulasiram58827** [comment]
@w-okada 

Environment: Intel i5 9th gen
Yes, I am using WebGL. Currently, I am getting around 25-30FPS.

How to throttle the fps? Is there any parameter in code to tweak to reduce the FPS and CPU utilization?

**Comment by w-okada** [comment]
@tulasiram58827

In my demo, there is no way to reduce FPS.
If you have AWS account, you can try https://github.com/w-okada/chime-videoprocess-ts .
This repository includes demo which uses meet segmentation with Amazon Chime SDK(video conference server).
