### ISSUE TITLE
tflite.wasm version

### ISSUE THREAD

**Issue by donaldong** [w-okada/image-analyze-workers#28]
Thanks for the amazing work so far :)

How is this file https://github.com/w-okada/image-analyze-workers/blob/master/011a_googlemeet-segmentation-tflite-worker-js/resources/tflite.wasm created? which tensorflow version was it using?

Not sure if it was generated using https://github.com/dsmilkov/tflite-wasm. Looks like in the latest tensorflow code, there's still no support for a wasm target yet.

**Comment by w-okada** [comment]
I used tensorflow v2.4.1. And you can build it with emscripten and toolchain.
https://github.com/emscripten-core/emsdk/tree/master/bazel/emscripten_toolchain

**Comment by donaldong** [comment]
Ah, thanks!

Do you have any plans for putting up the build scripts into this repo too?

Also, perhaps we can use a mediapipe.wasm -- it's what's currently in google meet also I believe.

**Comment by w-okada** [comment]
Probably No in this repository.
But I'm preparinig to write the blog entry how to generate.

**Comment by donaldong** [comment]
Amazing. Thank you!!

Looking forward to it.

**Comment by w-okada** [comment]
@donaldong 
I wrote blog.

https://dannadori.medium.com/build-tflite-wasm-simd-and-run-google-meet-virtual-background-6090226ed465
