### ISSUE TITLE
Comparing Google meet person segmentation demo with google meet

### ISSUE THREAD

**Issue by seanwong1127** [w-okada/image-analyze-workers#31]
This demo works very well already.
However, the effect of google meet will be a little better, probably because its edge blurring processing makes the effect a little better.

**Comment by w-okada** [comment]
The process is not disclosed as far as I know. My postprocessing is my own.
And if you have some idea to improve it, you can apply it to the output.

**Comment by w-okada** [comment]
Can I close this issue?
