### ISSUE TITLE
Another implementation: 60fps on mobiles

### ISSUE THREAD

**Issue by donaldong** [w-okada/image-analyze-workers#32]
Not sure if you have seen another project here: https://github.com/Volcomix/virtual-background 

It seems pretty production-ready, except for the segmentation model licensing part.

I think it'd also be cool for this project to also:
- have a video option in the demos
- have some performance results summary on the readme page, perhaps for mobile devices as well?

**Comment by w-okada** [comment]
Yes, I know. That is great work.

F.Y.I.
My demo also has the function to choose video input. 
I can use usb-cam, image file, movie file, screen capture.

![image](https://user-images.githubusercontent.com/48346627/113923235-455e0900-9823-11eb-86b5-9cd594bc583e.png)

**Comment by donaldong** [comment]
Ah, cool :) Thank you!
