### ISSUE TITLE
No segmentation in 011ademo_googlemeet-segmentation-tflite-worker-js-demo when process onLocal

### ISSUE THREAD

**Issue by huydq189** [w-okada/image-analyze-workers#34]
![image](https://user-images.githubusercontent.com/37098778/117242120-d1814180-ae5e-11eb-9d71-f034f9340551.png)

**Comment by huydq189** [comment]
"processOnLocal" : Can you explains what is role of this parameters in the web-app? Because when turn it "True" results output become distorted in black screen. And When keep it "False", it process normally

**Comment by huydq189** [comment]
![image](https://user-images.githubusercontent.com/37098778/117254044-24182900-ae72-11eb-9fca-01c9a7717907.png)
when i pull newest code

**Comment by huydq189** [comment]
![image](https://user-images.githubusercontent.com/37098778/117254286-6b9eb500-ae72-11eb-99f6-a54ce6518a76.png)
onLocal: False

**Comment by w-okada** [comment]
Thank you for your comment.
This is because package.json is old. I updated package.json.
please clone again and run npm install.

**Comment by huydq189** [comment]
Thank you for your response
I did clone again and now everything run normally
