### ISSUE TITLE
Predict return a full of 0 value array

### ISSUE THREAD

**Issue by huydq189** [w-okada/image-analyze-workers#35]
Hi w-okada, i'm working on a meteor project call Bigbluebutton
I import your segment tflite wasm successfully but when i use Predict() function it return a full of 0 value array
Do u have any idea what cause this ?
Thank you
Here is the log
![image](https://user-images.githubusercontent.com/37098778/117397406-44092480-af26-11eb-9770-a5d0e1754d67.png)

**Comment by huydq189** [comment]
The source was got from my webcam. i'am using navigator.mediastream

**Comment by huydq189** [comment]
nginx.conf
`
location /html5client {
  proxy_pass http://127.0.0.1:3000;
  proxy_http_version 1.1;
  proxy_set_header Upgrade $http_upgrade;
  proxy_set_header Connection "Upgrade";
}
`

the project use nginx to config the url , can it is the cause ?

**Comment by huydq189** [comment]
My code ![image](https://user-images.githubusercontent.com/37098778/117748241-dae12400-b239-11eb-90a7-e4741342945e.png)
Updated log
![image](https://user-images.githubusercontent.com/37098778/117748317-f51b0200-b239-11eb-8d4c-c995189422a9.png)

**Comment by w-okada** [comment]
Sorry for late response.
Which is Input image?
In your update log figure, left side image has no person...

**Comment by huydq189** [comment]
Thank you for your response
The input image is from my webcam stream
Before
![image](https://user-images.githubusercontent.com/37098778/117905390-4c35db00-b2fd-11eb-9ce6-34db49405ae8.png)
After
![image](https://user-images.githubusercontent.com/37098778/117905531-87d0a500-b2fd-11eb-8050-20ee5cb0cdef.png)
The predict return is Array full of 0
My param input:
        this.processOnLocal = true
        this.modelPath = '/html5client/resources/segm_lite_v681.tflite'
        this.enableSIMD = false
        this.kernelSize = 0
        this.useSoftmax = true
        this.usePadding = false
        this.threshold = 0.1
        this.useSIMD = false

        p.processWidth = 96
        p.processHeight = 160

**Comment by huydq189** [comment]
Problem solved. The cause is my tensorflow package in my package.json
