### ISSUE TITLE
High CPU usage with meet

### ISSUE THREAD

**Issue by RazaGR** [w-okada/image-analyze-workers#37]
is it normal that [tflite's meet code  for background removal ](https://github.com/w-okada/image-analyze-workers/tree/master/011a_googlemeet-segmentation-tflite-worker-js)is causing high CPU usage?

**Comment by w-okada** [comment]
Basically it depends on your PC or usecase.
This demo  processes the image each frame update, so the CPU usage is likely to become high. But if you use this model in video conference, for example, you need not use at high frequency.  May be 15fps or so is enough. In this situation, the CPU usage maybe more lower.

**Comment by RazaGR** [comment]
Thanks @w-okada , as you said, I need it for video conference, right now I am doing on every frame by using requestAnimationFrame on video play event, should I use `setTimeout` instead?  if so which value for timeout you think should be sufficient?

**Comment by w-okada** [comment]
Uuum,,, I have no idea. There are no established theory as fa as I know.

**Comment by RazaGR** [comment]
Thanks,  just setup a timeout on  `requestAnimationFrame`  and it works better, I also notice Google meet huge CPU.
