### ISSUE TITLE
011_googlemeet-segmentation-worker-js typescript error

### ISSUE THREAD

**Issue by ArtemOstapov** [w-okada/image-analyze-workers#39]
Doing everything with Readme I got the next **typescript error:**

```
google-segmentation-demo/src/App.tsx(39,66):
Argument of type 'number[][] | null' is not assignable to parameter of type 'number[][][]'.
  Type 'null' is not assignable to type 'number[][][]'.  TS2345
```

If I skip it with // @ts-nocheck, then I got the next **error:**
```
googlemeet-segmentation-worker.ts:276 Uncaught (in promise) TypeError: Cannot read property '0' of null
    at createForegroundImage (VM18322 googlemeet-segmentation-worker.ts:276)
```

`set config.processOnLocal = true `
that fixes previous error, but **dstCanvas** is white...

I think something is outdated

**Comment by w-okada** [comment]
I can not reproduce your problem.
If you use "011demo_googlemeet-segmentation-worker-js-demo", please update(git pull) and rerun.

**Comment by ArtemOstapov** [comment]
> I can not reproduce your problem.
> If you use "011demo_googlemeet-segmentation-worker-js-demo", please update(git pull) and rerun.

tnx for the quick answer,
i'm talking about **011_googlemeet-segmentation-worker-js**,
not **011demo_googlemeet-segmentation-worker-js-demo**

**Comment by w-okada** [comment]
OK, I fixed the readme.
