### ISSUE TITLE
Backgound blur effect in Google-meet Segmentation App

### ISSUE THREAD

**Issue by NaeemKhan333** [w-okada/image-analyze-workers#40]
@w-okada Thanks for such a nice work . I am trying to implement the background blur feature in the google meet segmentation app but unfortunately I could not do it . Can you provide the help or demo related to background blur effect for the google meet segmentation app.

**Comment by w-okada** [comment]
?
Sorry,,, I have no idea about what do you want...

**Comment by NaeemKhan333** [comment]
I want to blur the background rather than adding new background image.

**Comment by w-okada** [comment]
Sorry, I can not accept special order from you. 
Please consult an apropriate software developper.
And if you want to offer me, please email me.

And I close this issue.
