### ISSUE TITLE
Issue on running Safari Browser

### ISSUE THREAD

**Issue by NaeemKhan333** [w-okada/image-analyze-workers#42]
@w-okada Thank you very much for such a nice work . I have run the your Google meet application 

Link : https://github.com/w-okada/image-analyze-workers/tree/master/011demo_googlemeet-segmentation-worker-js-demo

It is working fine on Google Chrome and Firefox Browser , But it is not working on the Safari Web Browser . Does this application does not support the Safari Browser ?

**Comment by NaeemKhan333** [comment]
Any Update ?

**Comment by w-okada** [comment]
Note. some module is not provided as webworker for safari because of it's restriction.

**Comment by NaeemKhan333** [comment]
"MODNet" and "U2-Net Portrait Drawing" demo is working on the safari mac browser , but the "Google meet person segmentation" is not working. What I need to change in the app , so "Google meet person segmentation" demo work on the safari browser. Any suggestion ?
