### ISSUE TITLE
MODNet : Could not find a required file

### ISSUE THREAD

**Issue by NaeemKhan333** [w-okada/image-analyze-workers#43]
@w-okada Thank you very much for such a nice work . I am trying to run "MODNet Demo App" but It is giving me following error

App-Link : https://github.com/w-okada/image-analyze-workers/tree/master/010demo_modnet-worker-js-demo

```
ubuntu $ npm start

> 010demo_modnet-worker-js-demo@0.1.0 start
> react-scripts start

Could not find a required file.
  Name: index.js
  Searched in: /home/user/Downloads/image-analyze-workers-master/010demo_modnet-worker-js-demo/src
  
  ```

**Comment by w-okada** [comment]
I don't know the reason correctly. But, modules cause this.
I update the package.json and adjust the demo sample. Please re-try.
