### ISSUE TITLE
"Note: Safari is not supported with webworker. This porcess needs offscreencanvas."

### ISSUE THREAD

**Issue by myleftshoe** [w-okada/image-analyze-workers#48]
According to [caniuse](https://caniuse.com/webworkers) Safari ***does*** support webworkers!

[quote in title is from here](https://github.com/w-okada/image-analyze-workers/tree/master/012_barcode-scanner-worker-js#:~:text=Note%3A%20Safari%20is%20not%20supported%20with%20webworker.%20This%20porcess%20needs%20offscreencanvas)

Would like to use your lib - it looks fantastic.

**Comment by w-okada** [comment]
I'll check. please wait.

**Comment by w-okada** [comment]
Safari support webworker, but not support offscreencanvas.

https://caniuse.com/?search=offscreencanvas

**Comment by myleftshoe** [comment]
I misunderstood, it's clear now: the webworker uses offscreencanvas but safari does not support ofc.
